紅樓鍮  September 4, 2020


  0  Collapse this comment
Copy link
I think the when_all has another potentially undesirable behavior, namely an exception thrown by a task coming later in the argument list doesn’t fail the when_all until all earlier tasks have completed (or one of them itself throws an exception).  It also doesn’t handle lazy tasks like cppcoro::task<> correctly.





Raymond Chen Author
September 8, 2020


  0  Collapse this comment
Copy link
when_all doesn’t make any promises about which failure is reported if multiple operations fail. All it promises is that it completes when all the tasks have completed. (Or fails if any task fails.)




MGetz  September 4, 2020


  0  Collapse this comment
Copy link
I wish there was a setting on github to automatically decline PRs that include overloads of operator,()